services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=salman
    
    # env_file:
    #   - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql
      # - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
  
networks:
  postgres-network:
    